### ISSUE TITLE
World seam messed up and glitchy

### ISSUE THREAD

**Issue by nobodywasishere** [LunaSquee/minetest#2] opened 2018-03-29 15:54 UTC
##### Issue type
 - Bug report
 
##### Minetest version

```
minetest-0.5.0-dev-osx
```

##### OS / Hardware

Operating system: macOS Sierra
CPU: 2.3GHz Intel Core i5

GPU model: Intel Iris Plus Graphics 640 1536 MB

##### Summary

The world seem causes several problems with the current game, including walking through blocks and inability to mine certain places, along with graphical issues.

##### Steps to reproduce

Load up current version of LunaSquee/minetest and walk around until the seam is found.

##### Possible fix
Prevent the world from generating beyond the world seam?

![screen shot 2018-03-29 at 11 45 01](https://user-images.githubusercontent.com/32797552/38099335-58293606-3348-11e8-8456-3aa0d2e8c0b3.jpg)
![screen shot 2018-03-29 at 11 49 50](https://user-images.githubusercontent.com/32797552/38099338-5a4b4eb0-3348-11e8-98ad-35814a22354a.jpg)

**Comment by LunaSquee** [comment] 2018-03-29 16:07
Duplicate of #1

**Closed by LunaSquee** 2018-03-29 16:07 UTC
